version: 2
models:
  - name: orders_with_payments
    columns:
        - name: order_id
          tests:
            - not_null
            - relationships:
                to: ref('stg_orders')
                field: order_id

        - name: customer_id
          tests:
            - not_null
            - relationships:
                to: ref('stg_customers')
                field: customer_id

        - name: status
          tests:
            - accepted_values:
                values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
        - name: amount
          tests:
            - not_null