version: 2
models:
  - name: fct_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          - relationships:
                to: ref('stg_customers')
                field: customer_id